# Generated by Django 3.2.5 on 2023-05-28 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modules',
            name='treasury_active',
            field=models.BooleanField(default=True, verbose_name='تنشيط الخزائن'),
        ),
    ]
