# Generated by Django 3.2.5 on 2023-05-30 03:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Treasury',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treasury_name', models.CharField(max_length=100, verbose_name='اسم الخزينة')),
                ('treasury_date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الاضافة')),
                ('treasury_balance', models.FloatField(default=0.0, verbose_name='رصيد الخزينة')),
                ('deleted', models.BooleanField(default=False)),
                ('treasury_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='اضافة بواسطة')),
            ],
        ),
        migrations.CreateModel(
            name='TreasuryOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.IntegerField(choices=[(1, 'اضافة رصيد'), (2, 'سحب رصيد')], verbose_name='نوع العملية')),
                ('operation_value', models.FloatField(default=0.0, verbose_name='رصيد الخزنة')),
                ('operation_description', models.TextField(blank=True, max_length=200, null=True, verbose_name='وصف العملية')),
                ('operation_notes', models.TextField(blank=True, max_length=200, null=True, verbose_name='ملاحظات علي العملية')),
                ('operation_date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ العملية')),
                ('operation_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='انشاء بواسطة')),
                ('treasury', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Treasury.treasury', verbose_name='الخزينة')),
            ],
        ),
    ]
