# Generated by Django 3.2.5 on 2023-06-06 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Treasury', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treasuryoperation',
            name='operation_type',
            field=models.IntegerField(choices=[(1, 'اضافة رصيد'), (2, 'سحب رصيد')], default=0, verbose_name='نوع العملية'),
        ),
        migrations.AlterField(
            model_name='treasuryoperation',
            name='treasury',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Treasury.treasury', verbose_name='الخزينة'),
        ),
    ]
