# Generated by Django 3.2.5 on 2023-06-06 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Treasury', '0002_auto_20230606_0350'),
    ]

    operations = [
        migrations.AddField(
            model_name='treasuryoperation',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='treasuryoperation',
            name='operation_value',
            field=models.FloatField(default=0.0, verbose_name='قيمة العملية'),
        ),
    ]
