# Generated by Django 3.2.5 on 2023-06-13 06:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Treasury', '0004_rename_deleted_treasuryoperation_deleted_operation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treasuryoperation',
            name='operation_date',
            field=models.DateField(default=datetime.date.today, verbose_name='تاريخ العملية'),
        ),
    ]
