# Generated by Django 3.2.5 on 2023-05-07 20:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_alter_sellerpayments_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Factories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factoryinside',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المسئول'),
        ),
        migrations.AlterField(
            model_name='factoryinside',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Products.product', verbose_name='الموديل'),
        ),
        migrations.AlterField(
            model_name='factoryoutside',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المسئول'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المسئول'),
        ),
        migrations.AlterField(
            model_name='supplierpayment',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المسؤل'),
        ),
        migrations.AlterField(
            model_name='supplierquantity',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المسؤل'),
        ),
        migrations.AlterField(
            model_name='supplierquantity',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Products.product', verbose_name='الموديل'),
        ),
    ]
