# Generated by Django 3.2.5 on 2023-05-15 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Factories', '0002_auto_20230507_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factoryinside',
            name='product_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='عدد الموديل'),
        ),
    ]
