# Generated by Django 3.2.5 on 2023-05-19 14:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Workers', '0003_auto_20230515_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerpayment',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاريخ الاضافة'),
        ),
        migrations.AddField(
            model_name='workerpayment',
            name='description',
            field=models.CharField(max_length=250, null=True, verbose_name='وصف'),
        ),
        migrations.AlterField(
            model_name='workerattendance',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 5, 19, 14, 18, 57, 924048, tzinfo=utc), verbose_name='تاريخ الحضور'),
        ),
        migrations.AlterField(
            model_name='workerpayment',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 5, 19, 14, 18, 57, 924048, tzinfo=utc), verbose_name='تاريخ السحب'),
        ),
        migrations.AlterField(
            model_name='workerproduction',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 5, 19, 14, 18, 57, 924048, tzinfo=utc), verbose_name='تاريخ الاستلام'),
        ),
    ]
