# Generated by Django 3.2.5 on 2023-05-20 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Workers', '0004_auto_20230521_0029'),
        ('Workers', '0005_auto_20230519_1719'),
    ]

    operations = [
    ]
