# Generated by Django 3.2.5 on 2023-05-07 20:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerpayments',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 7, 23, 21, 54, 26831), verbose_name='التاريخ'),
        ),
    ]
