# Generated by Django 3.2.5 on 2023-05-15 19:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_alter_sellerpayments_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerpayments',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 15, 22, 1, 37, 280979), verbose_name='التاريخ'),
        ),
    ]
