# Generated by Django 3.2.5 on 2023-05-20 22:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_alter_sellerpayments_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerpayments',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 21, 0, 29, 33, 591582), verbose_name='التاريخ'),
        ),
    ]
