# Generated by Django 3.2.5 on 2023-05-28 17:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0005_alter_sellerpayments_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerpayments',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 28, 19, 40, 24, 835781), verbose_name='التاريخ'),
        ),
    ]
