# Generated by Django 3.2.5 on 2023-05-29 05:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0006_alter_sellerpayments_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerpayments',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 29, 7, 5, 37, 325426), verbose_name='التاريخ'),
        ),
    ]
