# Generated by Django 3.2.5 on 2023-06-06 03:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0016_alter_sellerpayments_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerpayments',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 6, 5, 11, 24, 538994), verbose_name='التاريخ'),
        ),
    ]
